--
-- PostgreSQL database dump
--

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2026-02-08 21:36:15

SET statement_timeout = 0;

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET transaction_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = on;

SELECT pg_catalog.set_config ('search_path', '', false);

SET check_function_bodies = false;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: adminm
--

-- *not* creating schema, since initdb creates it

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16595)
-- Name: caracteristicas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caracteristicas (
    idxxxx_caract integer NOT NULL,
    nombre_caract character varying(100) NOT NULL
);

ALTER TABLE public.caracteristicas OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16600)
-- Name: caracteristicas_idxxxx_caract_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.caracteristicas
ALTER COLUMN idxxxx_caract
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caracteristicas_idxxxx_caract_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- TOC entry 221 (class 1259 OID 16601)
-- Name: favoritos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favoritos (
    idxxxx_favori integer NOT NULL,
    status_favori boolean DEFAULT false,
    forane_mascot_id integer,
    forane_usuari_id integer
);

ALTER TABLE public.favoritos OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16606)
-- Name: favoritos_idxxxx_favori_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.favoritos
ALTER COLUMN idxxxx_favori
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favoritos_idxxxx_favori_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- TOC entry 223 (class 1259 OID 16607)
-- Name: formularioAdopcion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."formularioAdopcion" (
    idxxxx_forado integer NOT NULL,
    cedula_forado character varying(50) NOT NULL,
    nombre_forado character varying(255) NOT NULL,
    fnacim_forado date,
    correo_forado character varying(255),
    telefo_forado character varying(50),
    tvivie_forado character varying(100),
    propie_forado character varying(50),
    patjar_forado boolean,
    tampat_forado character varying(50),
    nperca_forado integer,
    masant_forado boolean,
    otrmas_forado boolean,
    nmasco_forado integer,
    motivo_forado text,
    ubimas_forado character varying(100),
    horasl_forado integer,
    encarg_forado character varying(255),
    veteri_forado boolean,
    gastos_forado boolean,
    elimin_logico boolean DEFAULT false,
    fechax_elimin timestamp without time zone
);

ALTER TABLE public."formularioAdopcion" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16616)
-- Name: formularioAdopcion_idxxxx_forado_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."formularioAdopcion"
ALTER COLUMN idxxxx_forado
ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."formularioAdopcion_idxxxx_forado_seq" START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- TOC entry 225 (class 1259 OID 16617)
-- Name: logs_edicion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.logs_edicion (
    idxxxx_logsed integer NOT NULL,
    fecambi_logsed timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    tabafe_logsed character varying(50) NOT NULL,
    camafe_logsed character varying(100) NOT NULL,
    valant_logsed text,
    valnue_logsed text,
    forane_regist_id integer,
    forane_usuari_id integer
);

ALTER TABLE public.logs_edicion OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16627)
-- Name: mascota_caracteristicas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mascota_caracteristicas (
    idxxxx_mascar integer NOT NULL,
    forane_mascot_id integer NOT NULL,
    forane_caract_id integer NOT NULL,
    status_mascar boolean
);

ALTER TABLE public.mascota_caracteristicas OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16633)
-- Name: mascota_caracteristicas_idxxxx_mascar_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mascota_caracteristicas
ALTER COLUMN idxxxx_mascar
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mascota_caracteristicas_idxxxx_mascar_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- TOC entry 228 (class 1259 OID 16634)
-- Name: mascotas; Type: TABLE; Schema: public; Owner: adminm
--

CREATE TABLE public.mascotas (
    idxxxx_mascot integer NOT NULL,
    nombre_mascot character varying(100) NOT NULL,
    especi_mascot character varying(50),
    sexoxx_mascot character varying(20),
    edadme_mascot integer,
    razaxx_mascot character varying(100),
    pesokg_mascot real,
    tamano_mascot character varying(50),
    infoad_mascot text,
    image1_mascot text,
    image2_mascot text,
    image3_mascot text,
    eliminado_logico boolean DEFAULT false,
    fecha_eliminacion timestamp without time zone,
    forane_usuari_id integer,
    status_mascot character varying,
    approv_mascot character varying(50) DEFAULT 'Pendiente'::character varying,
    fechap_mascot timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    nenerg_mascot character varying(20),
    vector_caracteristicas double precision[]
);

ALTER TABLE public.mascotas OWNER TO adminm;

--
-- TOC entry 229 (class 1259 OID 16644)
-- Name: mascotas_idxxxx_mascot_seq; Type: SEQUENCE; Schema: public; Owner: adminm
--

ALTER TABLE public.mascotas
ALTER COLUMN idxxxx_mascot
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mascotas_idxxxx_mascot_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- TOC entry 230 (class 1259 OID 16645)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    idxxxx_notifi integer NOT NULL,
    forane_usuari_id integer NOT NULL,
    type character varying(50) NOT NULL,
    message text NOT NULL,
    forane_solici_id integer,
    related_user_id integer,
    image_url character varying(255),
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16658)
-- Name: notifications_idxxxx_notifi_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications
ALTER COLUMN idxxxx_notifi
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_idxxxx_notifi_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- TOC entry 232 (class 1259 OID 16659)
-- Name: permisos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permisos (
    idxxxx_permis integer NOT NULL,
    nombre_permis character varying(100) NOT NULL,
    descri_permis text
);

ALTER TABLE public.permisos OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16666)
-- Name: permisos_idxxxx_permis_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.permisos_idxxxx_permis_seq AS integer START
WITH
    1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

ALTER SEQUENCE public.permisos_idxxxx_permis_seq OWNER TO postgres;

--
-- TOC entry 5186 (class 0 OID 0)
-- Dependencies: 233
-- Name: permisos_idxxxx_permis_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.permisos_idxxxx_permis_seq OWNED BY public.permisos.idxxxx_permis;

--
-- TOC entry 234 (class 1259 OID 16667)
-- Name: reviews; Type: TABLE; Schema: public; Owner: adminm
--

CREATE TABLE public.reviews (
    idxxxx_review integer NOT NULL,
    forane_usuari_id integer NOT NULL,
    conten_review text NOT NULL,
    nstars_review integer NOT NULL,
    fechax_review timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    eliminado_logico boolean DEFAULT false,
    fecha_eliminacion timestamp with time zone,
    CONSTRAINT reviews_nstars_review_check CHECK (
        (
            (nstars_review >= 1)
            AND (nstars_review <= 5)
        )
    )
);

ALTER TABLE public.reviews OWNER TO adminm;

--
-- TOC entry 235 (class 1259 OID 16679)
-- Name: reviews_idxxxx_review_seq; Type: SEQUENCE; Schema: public; Owner: adminm
--

CREATE SEQUENCE public.reviews_idxxxx_review_seq AS integer START
WITH
    1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

ALTER SEQUENCE public.reviews_idxxxx_review_seq OWNER TO adminm;

--
-- TOC entry 5188 (class 0 OID 0)
-- Dependencies: 235
-- Name: reviews_idxxxx_review_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: adminm
--

ALTER SEQUENCE public.reviews_idxxxx_review_seq OWNED BY public.reviews.idxxxx_review;

--
-- TOC entry 236 (class 1259 OID 16680)
-- Name: rol_permiso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol_permiso (
    idxxxx_rol_permiso integer NOT NULL,
    idxxxx_rolesx integer NOT NULL,
    idxxxx_permis integer NOT NULL
);

ALTER TABLE public.rol_permiso OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16686)
-- Name: rol_permiso_idxxxx_rol_permiso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.rol_permiso_idxxxx_rol_permiso_seq AS integer START
WITH
    1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

ALTER SEQUENCE public.rol_permiso_idxxxx_rol_permiso_seq OWNER TO postgres;

--
-- TOC entry 5190 (class 0 OID 0)
-- Dependencies: 237
-- Name: rol_permiso_idxxxx_rol_permiso_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.rol_permiso_idxxxx_rol_permiso_seq OWNED BY public.rol_permiso.idxxxx_rol_permiso;

--
-- TOC entry 238 (class 1259 OID 16687)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    idxxxx_rolesx integer NOT NULL,
    nombre_rolesx character varying(50) NOT NULL
);

ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 16692)
-- Name: roles_idxxxx_rolesx_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.roles_idxxxx_rolesx_seq AS integer START
WITH
    1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

ALTER SEQUENCE public.roles_idxxxx_rolesx_seq OWNER TO postgres;

--
-- TOC entry 5193 (class 0 OID 0)
-- Dependencies: 239
-- Name: roles_idxxxx_rolesx_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.roles_idxxxx_rolesx_seq OWNED BY public.roles.idxxxx_rolesx;

--
-- TOC entry 240 (class 1259 OID 16693)
-- Name: solicitudes_adopcion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.solicitudes_adopcion (
    idxxxx_solici integer NOT NULL,
    forane_solici_id integer NOT NULL,
    forane_public_id integer NOT NULL,
    forane_mascot_id integer NOT NULL,
    forane_forado_id integer NOT NULL,
    fechax_solici timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estado_solici character varying(50) NOT NULL,
    adosuc_solici boolean
);

ALTER TABLE public.solicitudes_adopcion OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16703)
-- Name: solicitudes_adopcion_idxxxx_solici_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.solicitudes_adopcion
ALTER COLUMN idxxxx_solici
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitudes_adopcion_idxxxx_solici_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- TOC entry 242 (class 1259 OID 16704)
-- Name: usuario_interacciones; Type: TABLE; Schema: public; Owner: adminm
--

CREATE TABLE public.usuario_interacciones (
    id integer NOT NULL,
    forane_idxxxx_usuari integer NOT NULL,
    forane_idxxxx_mascot integer NOT NULL,
    typexx_intera character varying(30) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.usuario_interacciones OWNER TO adminm;

--
-- TOC entry 243 (class 1259 OID 16712)
-- Name: usuario_interacciones_id_seq; Type: SEQUENCE; Schema: public; Owner: adminm
--

CREATE SEQUENCE public.usuario_interacciones_id_seq AS integer START
WITH
    1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

ALTER SEQUENCE public.usuario_interacciones_id_seq OWNER TO adminm;

--
-- TOC entry 5197 (class 0 OID 0)
-- Dependencies: 243
-- Name: usuario_interacciones_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: adminm
--

ALTER SEQUENCE public.usuario_interacciones_id_seq OWNED BY public.usuario_interacciones.id;

--
-- TOC entry 244 (class 1259 OID 16713)
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    idxxxx_usuari integer NOT NULL,
    nombre_usuari character varying(100) NOT NULL,
    emailx_usuari character varying(100) NOT NULL,
    contra_usuari character varying(255) NOT NULL,
    celula_usuari character varying(20),
    imagep_usuari text,
    mailve_usuari boolean DEFAULT false NOT NULL,
    tokeve_usuari character varying(255),
    tokexp_usuari timestamp with time zone,
    idxxxx_rolesx integer NOT NULL,
    reseto_usuari character varying(255),
    resetx_usuari timestamp with time zone,
    fecrea_usuari timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    feactu_usuari timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    apelli_usuari character varying(20),
    edadxx_usuari integer,
    vector_preferencias double precision[]
);

ALTER TABLE public.usuarios OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 16727)
-- Name: usuarios_idxxxx_usuari_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuarios_idxxxx_usuari_seq AS integer START
WITH
    1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

ALTER SEQUENCE public.usuarios_idxxxx_usuari_seq OWNER TO postgres;

--
-- TOC entry 5199 (class 0 OID 0)
-- Dependencies: 245
-- Name: usuarios_idxxxx_usuari_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuarios_idxxxx_usuari_seq OWNED BY public.usuarios.idxxxx_usuari;

--
-- TOC entry 4928 (class 2604 OID 16840)
-- Name: permisos idxxxx_permis; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permisos
ALTER COLUMN idxxxx_permis
SET DEFAULT nextval(
    'public.permisos_idxxxx_permis_seq'::regclass
);

--
-- TOC entry 4929 (class 2604 OID 16841)
-- Name: reviews idxxxx_review; Type: DEFAULT; Schema: public; Owner: adminm
--

ALTER TABLE ONLY public.reviews
ALTER COLUMN idxxxx_review
SET DEFAULT nextval(
    'public.reviews_idxxxx_review_seq'::regclass
);

--
-- TOC entry 4932 (class 2604 OID 16842)
-- Name: rol_permiso idxxxx_rol_permiso; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol_permiso
ALTER COLUMN idxxxx_rol_permiso
SET DEFAULT nextval(
    'public.rol_permiso_idxxxx_rol_permiso_seq'::regclass
);

--
-- TOC entry 4933 (class 2604 OID 16843)
-- Name: roles idxxxx_rolesx; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
ALTER COLUMN idxxxx_rolesx
SET DEFAULT nextval(
    'public.roles_idxxxx_rolesx_seq'::regclass
);

--
-- TOC entry 4935 (class 2604 OID 16844)
-- Name: usuario_interacciones id; Type: DEFAULT; Schema: public; Owner: adminm
--

ALTER TABLE ONLY public.usuario_interacciones
ALTER COLUMN id
SET DEFAULT nextval(
    'public.usuario_interacciones_id_seq'::regclass
);

--
-- TOC entry 4937 (class 2604 OID 16845)
-- Name: usuarios idxxxx_usuari; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
ALTER COLUMN idxxxx_usuari
SET DEFAULT nextval(
    'public.usuarios_idxxxx_usuari_seq'::regclass
);

--
-- TOC entry 5142 (class 0 OID 16595)
-- Dependencies: 219